### ISSUE TITLE
Stopped working about a day ago

### ISSUE THREAD

**Issue by romainrichard** [micso/easy-steamgifts#10]
Now seeing this in the Chrome console:
```
GET https://cdn.steamgifts.com/js/prebid_v2.js net::ERR_BLOCKED_BY_CLIENT                                  www.steamgifts.com/:101
Error in response to storage.get: TypeError: Cannot read property 'replace' of undefined                   (index):1
    at Object.getGiveawayData (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/visual.js:41:78)
    at HTMLDivElement.<anonymous> (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/visual.js:32:24)
    at Function.each (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/lib/jquery.min.js:2:5255)
    at init.each (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/lib/jquery.min.js:2:2011)
    at Object.getGiveawaysData (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/visual.js:31:36)
    at Object.getGiveaways (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/sg_lib.js:28:24)
    at sgRun (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/main_page.js:114:8)
    at Object.callback (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/main_page.js:107:9)
    at getLocalStorage (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/main_page.js:97:26)
    at Object.callback (chrome-extension://cklbilaeedbblhpkhjfcnmaocjdodcnm/main_page.js:63:9)
```

**Comment by gstavrinos** [comment]
Same here!

**Comment by Milouzze** [comment]
ESG no longer working for a few days now.

Join button no longer visible, blacklist and wishlist no longer taken into account.

Thanks in advance for your assistance.

**Comment by compujosh** [comment]
Same here, looks like SG made a layout change that broke it

**Comment by compujosh** [comment]
Created #11 to fix

**Comment by nemesistrk** [comment]
Auto load and hide options works but "Quick join button" doesnt show anymore.
